version: '3.8'

services:
  valkey:
    image: valkey/valkey:7.2
    container_name: idp_valkey
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:18
    container_name: idp_db
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=Ad54=Tx91.Vm+23_Qr78
      - POSTGRES_DB=rpp_qa
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: idp_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minio_password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  api:
    build: .
    container_name: idp_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 3
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - valkey
      - minio
      # - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    build: .
    container_name: idp_worker
    command: celery -A worker.celery_app worker --loglevel=info -c 1
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - valkey
      - minio
      # - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: node:lts
    container_name: idp_frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  minio_data:
  postgres_data:

